# bag
topic_lidar: /velodyne_points # /velodyne_packets #
topic_imu: /imu/data

LidarModel: VLP_16_points
vlp16_ring_case: 0

scan4map: 15.0
ndtResolution: 0.3 # 0.5 for indoor case and 1.0 for outdoor case
ndt_key_frame_downsample: 0.1
map_downsample_size: 0.25

knot_distance: 0.02
max_point_distance: 30  # ignore far points 

use_gui: false


segment_num: 1
selected_segment:
  - {start_time: 10, end_time: 40, path_bag: /home/daniel/Documents/HEMMA_kali_230105.bag} # set path to bag file, 10 first seconds are ignored. 30 seconds of data is used



plane_motion: false

# optimization weight
gyro_weight: 2.80  # factor to multiply the gyro measurement residuals
accel_weight: 1.85
lidar_weight: 1.0

lock_accel_bias: true

opt_timeoffset: true
timeoffset_padding: 0.01

opt_lidar_intrinsic: true
opt_IMU_intrinsic: true

iteration_num: 7  # number of calls of the refinement routine.

# For CalibParamManager
extrinsic:
  Trans: [0, 0, 0]  # position of lidar in IMU frame
  Trans_prior: [0, 0, 0]  # not used at all.
  Rot: [ 1.0000000, 0.0000000,  0.0000000,
         0.0000000, 1.0000000,  0.0000000,
          0.0000000,  0.0000000, 1.0000000]   # rotation of lidar relative to IMU frame
  # Trans: [0.3, 0.15, 0.05]

  # gt [1, 2, 5]deg
  # Rot: [  0.995588, -0.0871026,  0.0348995,
  #       0.0877492,    0.99599, -0.0174418,
  #     -0.0332403,  0.0204272,   0.999239]
